### ISSUE TITLE
Website/API

### ISSUE THREAD

**Issue by franciscop** [edent/SuperTinySocialIcons#1]
I repeat my comment here from HN:

This is really great. As someone who has done quite a few size-sensitive projects/experiments, have you considered providing them in a small website? So artists can contribute with more icons and developers who want to use them can modify them when downloading (border radius, background, etc). I could throw a quick prototype if that sounds good.

**Comment by edent** [comment]
Go ahead :-)

There are already lots of Icon / SVG sites. I got many of the original vectors from https://www.iconfinder.com/ - but I do like the idea of being able to change the border radius and background programatically.

I'm not sure about having people submit designs. User Generated Content is very hard moderate.

**Comment by franciscop** [comment]
That's really the main idea that I wanted for making it, to allow for user generated content to be uploaded. What would you do if people did a PR here with new logos?

However with a search I see that https://www.iconfinder.com/search/?q=facebook&price=free is really similar for instance (615 bytes one of them), so yeah it might not make sense to do that...

If we remove that functionality, it'd be only to modify the background+radius, which *could* (but maybe it shouldn't) just be statically generated and hosted in github. It'd be 51kb per logo folder approx: 1kb/logo * 50 (1-50%) + 1kb

**Comment by franciscop** [comment]
I have made a small preview site:

![radius_0](https://cloud.githubusercontent.com/assets/2801252/25078853/5c4cfb9a-2337-11e7-8683-95b7f04eaf0a.png)

![radius_5](https://cloud.githubusercontent.com/assets/2801252/25078851/5b8c9e18-2337-11e7-97a0-c22ca5961710.png)

![radius_8](https://cloud.githubusercontent.com/assets/2801252/25078852/5c2b72cc-2337-11e7-939a-d17338415be3.png)

![radius_32](https://cloud.githubusercontent.com/assets/2801252/25078854/5c88faf0-2337-11e7-8aef-2b851311acc8.png)
