### ISSUE TITLE
Some <g> elements can be removed

### ISSUE THREAD

**Issue by RazrFalcon** [edent/SuperTinySocialIcons#12]
Here is `flickr.svg` icon for example:

Before:
```xml
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
<rect fill="#ff0084" height="100%" rx="15%" width="100%"/>
<g fill="#fff">
<circle cx="150" cy="256" r="100"/>
<circle cx="365" cy="256" r="100"/>
</g>
</svg>
```
after:
```xml
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" fill="#fff">
<rect fill="#ff0084" height="100%" rx="15%" width="100%"/>
<circle cx="150" cy="256" r="100"/>
<circle cx="365" cy="256" r="100"/>
</svg>
```

**Comment by edent** [comment]
@ShaggyDude that's true - as it says in the README.  The goal of this is to create the Minimum Viable SVG.  The emphasis being on viable.

And, unless you're using the same icon multiple times, including the colour in the CSS doesn't save any space overall.

**Comment by ShaggyDude** [comment]
It adds some flexibility. Hovers, border radii. .. Splitting hairs though..

**Comment by RazrFalcon** [comment]
Outdated.
