### ISSUE TITLE
html5.svg contains useless path segments

### ISSUE THREAD

**Issue by RazrFalcon** [edent/SuperTinySocialIcons#13]
Does it need such details?

![1492349103_1920x1080_scrot](https://cloud.githubusercontent.com/assets/725494/25071477/4c308ebe-22c1-11e7-8d5a-ddb2d4a4bf31.png)

**Comment by edent** [comment]
Possibly not. I haven't done much hand editing of the files in Inkscape yet.

**Comment by RazrFalcon** [comment]
Ok.

**Comment by edent** [comment]
Fixed in #17
