### ISSUE TITLE
Skype is wrong color

### ISSUE THREAD

**Issue by 9mm** [edent/SuperTinySocialIcons#3]
It should be `#00AFF0`

**Comment by 9mm** [comment]
http://imjustcreative.com/skype-brand-identity-book-and-guidelines/2011/08/31

https://www.skype.com/en/legal/brand-guidelines/

**Comment by 9mm** [comment]
On a second glance, almost every single icon's color is off. Spotify is awful

**Comment by edent** [comment]
Most of these are taken from other sources - happy to accept pull requests with reference colours.
