### ISSUE TITLE
Why not use strokes?

### ISSUE THREAD

**Issue by proimage** [edent/SuperTinySocialIcons#34]
A number of the icons ([PDF](https://github.com/edent/SuperTinySocialIcons/blob/master/tiny/pdf.svg), [RSS](https://github.com/edent/SuperTinySocialIcons/blob/master/tiny/rss.svg), [Wire](https://github.com/edent/SuperTinySocialIcons/blob/master/tiny/wire.svg), etc) could be represented in fewer bytes by applying a stroke to a path, instead of it being an outlined and enclosed shape. Any particular reason why this hasn't been done?

**Comment by edent** [comment]
The reason is... I'm still learning about SVG ☺️😊😀😁😁

If strokes will make them smaller - go for it! Submit a pull request and let's save the world a few more bytes!

**Comment by RazrFalcon** [comment]
At least PDF icon can't be done like this.

**Comment by proimage** [comment]
> At least PDF icon can't be done like this.

Oh?

```
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
<rect fill="#f00" height="512" rx="15%" width="512"/>
<path d="m 257,109 c -2,-62 -50,-47 -48,11 3,70 29,90 68,139 49,62 86,97 116,105 45,12 70,-26 26,-45 -43,-19 -122,-13 -167,-6 -74,12 -127,33 -168,79 -36,40 -4,70 32,35 33,-31 77,-116 95,-156 24,-53 51,-100 46,-168 z" style="fill:none;stroke:#fff;stroke-width:27"/>
</svg>
```

388 bytes.

**Comment by RazrFalcon** [comment]
You right. I thought it will look too wavy.

Can you send a pull request with this icon? But remove `style` attribute.
