### ISSUE TITLE
Meetup icon

### ISSUE THREAD

**Issue by yarons** [edent/SuperTinySocialIcons#39]
Hi there,

I really like your icons and especially the fact that they all load super fast.

I was wondering if you can please add an icon for [Meetup.com](http://meetup.com).
There are several samples [here](https://www.shareicon.net/tag/meetup?p=2).
The official press logo is [here](https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/8/f/1/d/highres_454596637.jpeg).

Thank you

**Comment by edent** [comment]
Thank you!

That Meetup icon sure is ugly though :-(

**Comment by gwire** [comment]
I recently switched the footer icons on [Open Rights Group](https://www.openrightsgroup.org/) to these svg icons, and needed to knock up a quick Meetup icon here: [meetup.svg](https://www.openrightsgroup.org/assets/images/site/icons/social/svg/meetup.svg)

**Comment by RazrFalcon** [comment]
Made a smaller version (625B):
```svg
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
  <rect fill="#ed1c40" height="512" rx="15%" width="512"/>
  <path d="m442 114c79 13 30 113 11 152-12 26-72 129-20 145 16 4 36 2 49 13 23 20 2 37-18 42-23 6-51 0-72-10-69-30-53-106-23-157 13-28 38-59 44-82 4-20-16-38-34-17-11 13-20 32-27 47-8 16-48 103-48 103-7 14-20 34-33 45-22 17-57 6-51-23 8-47 81-157 31-164-18-2-24 18-30 31-10 22-16 45-27 67-12 25-22 51-28 78-5 22-12 50-36 56-68 18-89-26-89-26-11-35-1-67 10-101 8-26 13-53 24-78 18-45 37-137 105-131 17 2 36 11 51 19 40 26 54-20 80-25 21-5 33 4 46 14 21 18 27 7 40 5 12-3 29-6 45-3z" fill="#fff"/>
</svg>
```

It's hard to make such curvy icon with pixel rounding. So it's a bit different.

**Comment by edent** [comment]
@RazrFalcon love it! PR please, if you have the time.

**Comment by RazrFalcon** [comment]
I still have a write access, actually. So I can push it directly to the repo. Is it ok?

**Comment by edent** [comment]
Yup :-)

**Comment by RazrFalcon** [comment]
I've noticed that previous icons was bigger that 400x400, so I remade it and now it's even smaller.
