### ISSUE TITLE
Google Plus is wrong

### ISSUE THREAD

**Issue by edent** [edent/SuperTinySocialIcons#4]
New style G is needed - see https://play.google.com/store/apps/details?id=com.google.android.apps.plus

Not that anyone uses it.

**Comment by j6k4m8** [comment]
Why is there no _ziiiiiiing_ GitHub Reaction icon yet?

(This should make the SVG way smaller too, since the new shape is so much less complex.)

**Comment by j6k4m8** [comment]
I saved a few bytes by making the "+" two overlapping rects (saves the four concave corners)...

Mostly just sour that you managed to push this so quick while I was still working on mine! :)

**Comment by edent** [comment]
If it's smaller - please raise a PR :-)
