### ISSUE TITLE
How to group several icons in one SVG file to reduce # of requests

### ISSUE THREAD

**Issue by claudiobrandt** [edent/SuperTinySocialIcons#46]
Hi Terence,

Great job with these super tiny icons. Thanks.
I wonder how I would go about grouping 4 or 5 icons inside one SVG file, to reduce the number of requests. I'm not a programmer, but like to mess around, so please forgive me if this is too basic a question. 

Best regards,
Claudio

**Comment by kokarn** [comment]
The easiest way is to wrap them with id's and just merge them in a single
svg file. Then just reference them as symbols

Here's a good link that helps with that
https://css-tricks.com/svg-symbol-good-choice-icons/

**Comment by edent** [comment]
You can also print them directly into the HTML of your page. 

Take a look at the source code to https://edent.tel/

**Comment by claudiobrandt** [comment]
Hello, @kokarn and @edent. 
Both methods worked, but since I'm dealing with a small number of icons that will go together in every page of the site, I've opted to include them directly into the HTML, as suggested by @edent. 
Thanks!

**Comment by kokarn** [comment]
Yeah it's by far the better one, it's the one I use as well :-) Good
choice!
