### ISSUE TITLE
Line icon is missing?

### ISSUE THREAD

**Issue by skatkov** [edent/SuperTinySocialIcons#47]
Line is very popular messenger in Asia. Any chance you can add it?

https://media.line.me/en/how_to_install#lineitbutton

**Comment by edent** [comment]
Sounds good! You can either send a Pull Request - or tell us where we can find an SVG.

**Comment by skatkov** [comment]
@edent how about this one?
https://worldvectorlogo.com/logo/line-messenger

**Comment by RazrFalcon** [comment]
Done. 455 bytes.

**Comment by skatkov** [comment]
Great! Thank you @RazrFalcon for help!
