### ISSUE TITLE
VK.com icon?

### ISSUE THREAD

**Issue by exebook** [edent/SuperTinySocialIcons#7]

**Comment by edent** [comment]
I don't know the site. If you can find me an open source SVG copy of their logo, I can try to shrink it.

**Comment by tkalmi** [comment]
VK.com is the Russian version of Facebook. Here's an SVG of their logo https://commons.wikimedia.org/wiki/File:VK.com-logo.svg 
It's in wikimedia so I suppose it's open source enough.
