### ISSUE TITLE
Should have a google G icon

### ISSUE THREAD

**Issue by Teovald** [edent/SuperTinySocialIcons#8]
In addition to the google + icon, there should also be a google icon for google login : 
https://developers.google.com/identity/

like this one : https://commons.wikimedia.org/wiki/File:Google_%22G%22_Logo.svg

Google login used to be tied to Google+ but it has been separated from the + brand a while ago.

**Comment by edent** [comment]
I've added it!

Closed in https://github.com/edent/SuperTinySocialIcons/commit/a87de76b6e77bb6ced193e672e65471c07d6f27d
